version: '3'

services:
  dormitory_room:
    build:
      context: ./dormitory_room
      dockerfile: Dockerfile
    restart: always
    environment:
      DORMITORY_STUDENT_URL: "http://dormitory_student:8080"

  dormitory_student:
    build:
      context: ./dormitory_student
      dockerfile: Dockerfile
    restart: always

  dormitory_gateway:
    build:
      context: ./dormitory_gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      DORMITORY_STUDENT_URL: "http://dormitory_student:8080"
      DORMITORY_ROOM_URL: "http://dormitory_room:8080"
      DORMITORY_GATEWAY_HOST: "dormitory_gateway:8080"

  dormitory_angular:
    build:
      context: ./dormitory_angular
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: http://dormitory_gateway:8080/api
    ports:
      - "8083:80"