### Get all rooms

GET http://localhost:8080/api/rooms

### create/update
PUT http://localhost:8080/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
Content-Type: application/json

{
  "name": "P100",
  "bedsNumber": 4
}

### Get room by id
GET http://localhost:8080/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

### Deleting room by Id

DELETE http://localhost:8080/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6



### Get all students

GET http://localhost:8080/api/students

### create/update

PUT http://localhost:8080/api/students/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Content-Type: application/json

{
  "name": "Bob",
  "surname": "Bobob",
  "room": "ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197"
}

### Get student by Id

GET http://localhost:8080/api/students/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76


### Deleting student by Id

DELETE http://localhost:8080/api/students/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76