### Get all rooms

GET http://localhost:8082/api/rooms

### create/update
PUT http://localhost:8082/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f0aaa
Content-Type: application/json

{
  "name": "P100",
  "bedsNumber": 4
}

### get students in room
GET http://localhost:8082/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

### Get room by Id

GET http://localhost:8082/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

### Deleting room by Id

DELETE http://localhost:8082/api/rooms/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6




### Get all students

GET http://localhost:8080/api/students

### create/update

PUT http://localhost:8080/api/students/e16a8784-c95d-498a-8fb0-2f781e331553
Content-Type: application/json

{
  "name": "Bob",
  "surname": "Bobob",
  "room": "03619986-6413-45d5-a98c-cc7d58cf0b28"
}

### Get student by Id

GET http://localhost:8080/api/students/7ef19af6-7a39-482c-a6bb-871d3b5d8c9b


### Deleting student by Id

DELETE http://localhost:8080/api/students/e86157e9-d75e-4f31-aae5-76e2eb195cd0